export const UPDATE_LOGIN = 'UPDATE_LOGIN';
export const REQUEST_AUNTIFICATION = 'REQUEST_AUNTIFICATION';
export const REQUEST_AUNTIFICATION_SUCCESS = 'REQUEST_AUNTIFICATION_SUCCESS';
export const REQUEST_AUNTIFICATION_FAIL = 'REQUEST_AUNTIFICATION_FAIL';
export const AUNTIFICATION_STATUS_RESET = 'AUNTIFICATION_STATUS_RESET';